### PR TITLE
Return rows with null values. Only show fill value input for time series

### LINKED ISSUE #110: Plugin always returns the previous value of a field for a NULL value in query
**Plugin always fills missing values with the previous value instead of the option configured in Grafana Query Editor**:

**What you expected to happen**:
When "Fill Value" is configured to NULL, the fields having NULL values should return NULL.

**How to reproduce it (as minimally and precisely as possible)**:

1. Configure Fill Value as NULL in Query Editor
2. Fire a query returning NULL values in the raw query
3. Check the data retrieved by the redshift data source plugin 

**Screenshots**

Fill Value configured to NULL
image

Actual Redshift query executed in Redshift query editor in AWS
image

In grafana redshift query inspector, 
image

**Anything else we need to know?**:
We have looked into the codebases of sqlds, grafana-sdk-plugin-go, athena and clickhouse datasources, the fillmode seems to be set and used correctly, so not sure what the issue is. The only distinct thing that we found was clickhouse datasource configures the fillmode using the Fillmode() method and not the Settings(), as is there in the sqlds driver.

**Environment**:
- Grafana version: 8.3.0
- Plugin version: 1.0.1
- OS Grafana is installed on: Linux
- User OS & Browser: Tested on Safari & Chrome
- Others:

### PR DESCRIPTION
**Pull request by andresmgot**
Fixes #110 

This PR fixes the following:

> There are two different issues here:
> - The Fill Value input only applies when the frames are formatted as Time Series. This is used to fill frames in the Time Series panel. We should not show it for table frames since it's indeed confusing.
> - Null values should be returned as `null` not the previous value (this is the behavior of the PostgreSQL data source, for example).

Screenshot from 2022-01-18 13-07-24

### CODE REVIEW

File: pkg/redshift/driver/rows.go [hunk 1]
```diff
@@ -201,6 +201,7 @@ func (r *Rows) fetchNextPage(token *string) error {
 func convertRow(columns []*redshiftdataapiservice.ColumnMetadata, data []*redshiftdataapiservice.Field, ret []driver.Value) error {
 	for i, curr := range data {
 		if curr.IsNull != nil && *curr.IsNull {
+			ret[i] = nil
```
Comment (andresmgot) [inline pkg/redshift/driver/rows.go:204]: not setting the `ret`urned value for a certain index was what caused the previous value to be used.

Comment (fridgepoet) [reply pkg/redshift/driver/rows.go:204]: wow, looks like this was quite difficult to catch!

File: pkg/redshift/driver/rows_test.go [hunk 2]
```diff
@@ -383,6 +383,19 @@ func Test_convertRow(t *testing.T) {
 			expectedValue: `2021-07-15 14:00:00 +0000 UTC`,
 			Err:           require.NoError,
 		},
+		{
+			name: "null",
+			metadata: &redshiftdataapiservice.ColumnMetadata{
+				Name:     aws.String("id"),
+				TypeName: aws.String(REDSHIFT_INT8),
```
Comment (fridgepoet) [inline pkg/redshift/driver/rows_test.go:390]: This `TypeName` field can be removed in this test case.
(It might not be a realistic representation of that data, but that documents that this field is irrelevant, i.e. the code doesn't even use it.)

**Review by fridgepoet — COMMENTED** [review]
It would be nice to have a backend test that demonstrates the original reported bug (at least a couple of incoming values in a slice) and that it now passes with the expected entry set to `nil`.

**Comment by fridgepoet** [comment]
👍  Go changes look good to me

**Review by sunker — APPROVED** [review]
Nice!
