### PR TITLE
Fix converting rows with FLOAT4 and BOOLEAN

### LINKED ISSUE #204: Time Series query error with Redshift 'REAL' data type
**What happened?**
When trying to create a Time Series visualization with a Redshift data source that has a column with data type `REAL`, the query fails with an `HTTP 500 - Internal Server Error`.

The same query is running on the same column with `int` data type works.

**What was expected to happen?**
Queries on REAL data type columns should also complete successfully.

**Steps to reproduce the problem:**
1. Create a redshift cluster with a column with `int` data type
2. Create a Time Series dashboard in Grafana
3. Run a time series query that selects this `int` data type column
4. Create additional column in redshift with `real` data type, and copy over int data to the `real` data type column
5. Modify time series query to use `real` datatype column instead
6. Query fails with "Internal Server Error" (see attached screenshot)

**Version numbers (grafana, prometheus, graphite, plugins, operating system, etc.):**
Grafana version: v8.4.7
Redshift version: v1.3.0
OS: Amazon Linux 2

**Configuration information:**
Redshift table schema is also attached as screenshot.

### PR DESCRIPTION
**Pull request by iwysiu**
From investigating with our external dev credentials, it looks like we were converting Float4 and Boolean from the wrong types. When I set the redshift column to the REAL type, it returned a Float4, so I don't think our issue was that we weren't supporting the type. Also, I suspect that the FLOAT type should also be converted as a double, but in Redshift it's synonymous with DOUBLE and I couldn't get it to actually return that type. 
I'm a little suspicious of the solution because it implies either that FLOAT4 has never worked or that AWS changed the return type.

Fixes #204

### CODE REVIEW

**Review by fridgepoet — APPROVED** [review]

**Comment by fridgepoet** [comment]
Nice, thanks for checking this!

Do you think we should just consider FLOAT the same case as FLOAT8? It's what I'm seeing for the DOUBLE PRECISION column type. 

> I'm a little suspicious of the solution because it implies either that FLOAT4 has never worked or that AWS changed the return type.

Same about the boolean, right? 

By the way, for future reference if we want to test this out, it's much easier to write a query like `SELECT CAST('123456' AS REAL);` than to create a cluster/table/column of a certain type.

File: pkg/redshift/driver/rows_test.go [hunk 1]
```diff
@@ -126,13 +126,14 @@ func Test_convertRow(t *testing.T) {
 		{
 			name: "numeric type float4",
 			metadata: &redshiftdataapiservice.ColumnMetadata{
+				Name:     aws.String("other"),
```
Comment (fridgepoet) [inline pkg/redshift/driver/rows_test.go:129]: Just wondering out loud: Regarding all the special checks for `time` column (https://github.com/grafana/redshift-datasource/issues/62), I wonder why we don't ever do it for other "number" types. Or why we don't somehow ensure it is PostgresSQL before just going for the assumption it is Unix time.
